name: new_flutter_ayetstudios
description: The new flutter ayestudios plugin.
version: 1.1.1
homepage: https://github.com/Maciejj1/new_flutter_ayet

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.anavrinapps.flutter_ayetstudios
        pluginClass: FlutterAyetstudiosPlugin
      ios:
        pluginClass: FlutterAyetstudiosPlugin

